config/routes.rb
Rails.application.routes.draw do
  resources :gossips do
    resources :comments, except: [:index, :new, :show]
    resources :likes, only: [:create, :destroy]
  end
  resources :users
  resources :cities
  resources :sessions, only: [:new, :create, :destroy]
  root 'gossips#index'
  get 'team', to: 'static#team'
  get 'contact', to: 'static#contact'
  get 'hidden/:person', to: 'user#hidden', as: 'hidden_person'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  validates :name,
    presence: true
  validates :zip_code,
    presence: true,
    uniqueness: true,
    format: { with: /\A(([0-8][0-9])|(9[0-5])|(2[ab]))[0-9]{3}\z/, message: "please enter a valid french zip code" }

    has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content,
    presence: true
  belongs_to :user
  belongs_to :gossip  
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title,
  presence: true,
  length: {minimum: 3, maximum: 14}
  validates :content,
  presence: true

  belongs_to :user
  has_many :tag_gossip_links
  has_many :tags, through: :tag_gossip_links
  has_many :comments
  has_many :likes


  def likes_amount
    self.likes.length
  end

end

app/models/like.rb
class Like < ApplicationRecord
validates :gossip_id, uniqueness: { scope: :user_id,
    message: "only one like per user per gossip" }

  belongs_to :gossip
  belongs_to :user
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  validates :content, 
    presence: true

  belongs_to :sender, class_name: "User"
  has_many :recipient_to_pm_links, foreign_key: 'received_message_id'
  has_many :recipients, foreign_key: 'recipient_id', class_name: "User", through: :recipient_to_pm_links
end

app/models/recipient_to_pm_link.rb
class RecipientToPmLink < ApplicationRecord
  belongs_to :recipient, class_name: "User"
  belongs_to :received_message, class_name: "PrivateMessage"
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :title, 
    presence: true
    
  has_many :tag_gossip_links
  has_many :gossips, through: :tag_gossip_links
end

app/models/tag_gossip_link.rb
class TagGossipLink < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :description, presence: true
  validates :age, presence: true
  validates :password, presence: true, length: {minimum: 6}

  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :recipient_to_pm_links, foreign_key: 'recipient_id'
  has_many :received_messages, foreign_key: 'received_message_id', class_name: "PrivateMessage", through: :recipient_to_pm_links
  has_many :comments
  has_many :likes
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  def show
  	@city = City.find(params[:id])
  end
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
  def index()
    @success=params[:success]
    @gossips = Gossip.all.reverse
  end

  def show
    @gossip = Gossip.find(params[:id])
  end

  def new
  end
  
  def create
    @gossip = Gossip.new(title: params[:title], content: params[:content], user: User.find(11))

    if @gossip.save  
      redirect_to gossip_index_path(success: true)
    else
      render 'new'
    end
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, only: [:create, :new, :edit, :destroy]
  before_action :is_gossip_author?, only: [:edit, :update, :destroy]
  
  def index()
    @success=params[:success]
    @gossips = Gossip.order(:id).reverse
  end

  def show
    @success = params[:success]
    @gossip = get_gossip
    @comments = Comment.where(gossip_id: @gossip.id)
  end

  def new
  end

  def create
    @gossip = Gossip.new(title: params[:title], content: params[:content], user: current_user)

    if @gossip.save
      redirect_to gossips_path(success: true)
    else
      render 'new'
    end
  end

  def edit
    @gossip = get_gossip
  end

  def update
    @gossip = get_gossip

    if @gossip.update(
      title: params[:title],
      content: params[:content]
      )
    redirect_to gossip_path(params[:id], success: true)
  else
    render :edit
  end
end

def destroy
  @gossip = get_gossip
  @gossip.destroy

  redirect_to gossips_path
end

private

def get_gossip
  Gossip.find(params[:id])
end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user, only: [:create, :destroy]

  def create
    @like = Like.create(user: current_user, gossip: Gossip.find(params[:gossip_id]))
    puts @like.errors.messages
    redirect_back(fallback_location: root_path)
  end

  def destroy
    likes = Like.where(user: current_user, gossip: Gossip.find(params[:id]))
    likes.each do |like|
      like.destroy
    end
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def contact
  end
  def team
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @author = User.find(params[:id])
  end

  def hidden
    @person = params[:person]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @cities = get_city
  end

  def create
    begin
      @user = User.new(
        first_name: params[:first_name],
        last_name: params[:last_name],
        age:params[:age],
        city: City.find(params[:city]),
        description: params[:description],
        email: params[:email],
        password: params[:password],
        password_confirmation: params[:password_confirmation]
        )

      if @user.save
        flash.now[:success] = "Nouvel utilisateur enregistré"
        log_in(@user)
        redirect_to root_path
      else
        flash.now[:error] = "Tu as du oublier de remplir des informations mon petit chat"
        @cities = get_city
        render 'new'
      end
    rescue Exception => e
      flash.now[:error] = e.message
      @cities = get_city
      render "new"
    end
  end

  def show
    @author = User.find(params[:id])
  end

  def hidden
    @person = params[:person]
  end

  private

  def get_city
   City.all.order("name")
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end

  def is_gossip_author?
    unless current_user == User.find_by(gossips: Gossip.find(params[:id]))
      flash[:danger] = "Tu n'es pas l'auteur de ce potin."
      redirect_to root_path
    end
  end

  def is_comment_author?
    unless current_user == User.find_by(comments: Comment.find(params[:id]))
      flash[:danger] = "Tu n'es pas l'auteur de ce commentaire."
      redirect_to root_path
    end
  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/gossip/create.html.erb
<div class="text-center">
    <h1>SOON A NEW FEATURE</h1>
    <h2>ADD A NEW GOSSIP</h2>
    <p>
        But until then, you can check the gossips already written<br/>
        <a href="<%= root_path%>" class="btn btn-primary">Return to home</a>
    </p>
</div>

app/views/gossips/edit.html.erb
<% gossip = @gossip ? @gossip : Gossip.new(title: "", content:"")%>

<% if gossip.errors.any? %>
  <aside class="alert alert-danger">
    <p>Nous n'avons pas réussi à mettre à jour le potin pour la (ou les) raison(s) suivante(s) :</p>
    <ul>
      <% gossip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </aside>
<% end %>

<div class="card text-center">
  <div class="card-header">
    <h1>Edition de ton potin ! </h1>
  </div>

<!-- formulaire de création de gossip form_tag -->

  <%= form_tag url_for(action: 'update'), method: 'PUT', class:"card-body" do %>
    <div class="form-group">
      <%= label_tag 'title', 'Titre' %>
      <%= text_field_tag 'title', gossip.title, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= label_tag 'content', 'Contenu' %>
      <%= text_area_tag 'content', gossip.content, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= submit_tag "Editer potin", class: "btn btn-info"%>
    </div>
  <% end %>

<!-- ... -->
  <div class="card-footer text-muted">
    <p>
      <br/>
      <a href="<%= root_path%>" class="btn btn-primary">Retour à l'accueil</a>
    </p>
  </div>
</div>

app/views/gossips/index.html.erb
  <% if @success %>
  <div class="alert alert-success">
    <p>Nouveau potin bien enregistré</p>
  </div>
  <% end %>

  <!-- Jumbotron Header -->
  <header class="jumbotron my-4">

    <h1 class="display-3">The Gossip Project </h1>
    <p class="lead">Wesh wesh canne à pêche. Bienvenue sur la page d'acceuil du meilleur Gossip Project qui à intérêt à sortir dans le top 1 des meilleurs projet parce que franchement tu vas voir il tue sa mère. Mais si tu l'aime pas c'est pas grave nous on aime bien quand même koeur koeur bisous.
      😘😘
    </p>
    <p class='text-center'>
      <a href="<%= new_gossip_path %>" class="btn btn-primary btn-lg">Ajouter un gossip</a>
    </p>
  </header>

  <% @gossips.each_with_index do |gossip,i| %>
  <div class="card text-center">
    <div class="card-header">
      <h6> Gossip n° <%=i+1%> de : <%= gossip.user.first_name %> <%= gossip.user.last_name %></h6>
    </div>
    <div class="card-body">
      <h5 class="card-title"><%= gossip.title %></h5>
      <p class="card-text"><%= gossip.content %></p>
      <a href="<%= gossip_path(gossip.id)%>" class="btn btn-primary">En savoir plus</a>
      <!--Likes-->
      <% already_liked=false%>
      <% gossip.likes.each do |like|%>
      <%if like.user == current_user then already_liked = true end%>
      <%end%>
      <%case already_liked %>
      <%when false %>
      <a class= "btn btn-secondary" data-method= "post" href="<%= gossip_likes_path(id: gossip.id, gossip_id: gossip.id) %>"> 👍</a>
      <%when true %>
      <a class= "btn btn-success active" data-method= "delete" href="<%= gossip_like_path(id: gossip.id, gossip_id: gossip.id) %>"> 👍</a>
      <%end%>
      <!--Footer-->
    </div>
    <div class="card-footer text-muted">
      <p>Modifié le : <%= gossip.updated_at.strftime("%Y-%m-%d %H:%M:%S") %></p>
      <p><%= gossip.comments.count %> commentaire<%= "s" if gossip.comments.count > 1 %>
       - <%= gossip.likes.count %> like<%= "s" if gossip.likes.count > 1 %></p>
     </div>
   </div>
   <% end %>
   <!-- /.container -->

app/views/gossips/new.html.erb
<% gossip = @gossip ? @gossip : Gossip.new%>

<% if gossip.errors.any? %>
  <aside class="alert alert-danger">
    <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
    <ul>
      <% gossip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </aside>
<% end %>

<div class="card text-center">
  <div class="card-header">
    <h1>Création de ton gossip ! </h1>
    <h2>Viens rejoindre la communauté des fdp qui balancent des gossips comme des ados de 15 ans en pleine puberté qui matent trop Gossip Girl ❤️️</h2>
  </div>

<!-- formulaire de création de gossip form_tag -->

  <%= form_tag url_for(action: 'create'), method: 'POST', class:"card-body" do %>
    <div class="form-group">
      <%= label_tag 'title', 'Titre' %>
      <%= text_field_tag 'title', gossip.title, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= label_tag 'content', 'Contenu' %>
      <%= text_area_tag 'content', gossip.content, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= submit_tag "Créer potin", class: "btn btn-primary"%>
    </div>
  <% end %>

<!-- ... -->
  <div class="card-footer text-muted">
    <p>
      <br/>
      <a href="<%= root_path%>" class="btn btn-primary">Retour à l'accueil </a>
    </p>
  </div>
</div>

app/views/gossips/show.html.erb
<%
author = @gossip.user
comment = @comment ? @comment : Comment.new
%>

<% if @success %>
<div class="alert alert-success">
  <p>Nouveau potin bien modifié</p>
</div>
<% end %>

<div class="card text-center">
    <div class="card-header">
      <h1><%= @gossip.title %></h1>
      <h3> 👍 <%=@gossip.likes_amount%> 👍 </h3>
    </div>
    <div class="card-body">
      <h2 class="card-title">
        <small>de <%= link_to author.first_name + " " + author.last_name, user_path(author.id)%> ( <%=  link_to author.city.name,  city_path(author.city.id)%> ) </small>
      </h2>
      <blockquote class="card-text display-4"><%= @gossip.content %></blockquote>
      <% if current_user == author %>
      <p><%=link_to "Editer", edit_gossip_path(@gossip.id), class: "btn btn-info" %>
        <a href="<%= gossip_path(@gossip.id) %>" class="btn btn-danger" data-method= "delete" data-confirm= "T'en es certain ?">Supprimer</a>
      </p>
      <% end %>
      <hr />
      <div id="comment-zone">
        <h3>Commentaires</h3>
        <% unless @comments.empty? %>
          <% @comments.each do |comment|%>
            <div class="comment">
              <p><strong><%= comment.user.first_name + " " + comment.user.last_name %></strong></p>
              <div><%= comment.content %></div>
              <% unless current_user == comment.user %>
                <p style="visibility: hidden">
              <%else%>
                <p>
              <% end %>
                  <%= link_to "Modifier", edit_gossip_comment_path(@gossip.id, comment.id), class: "btn btn-warning"%>
                </p>
            </div>
          <% end %>
        <% else %>
          <p>Pas encore de commentaire.</p>
        <% end%>
        <form action="<%= gossip_comments_path(@gossip.id)%>" method='post'>
          <div class="form-group">
            <%= label_tag 'content', 'Contenu' %>
            <%= text_area_tag 'content', comment.content, class: "form-control" %>
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
          </div>
          <div class="form-group">
            <%= submit_tag "Commenter", class: "btn btn-secondary"%>
          </div>
        </form>
        <!--Likes-->
      <% already_liked=false%>
      <% @gossip.likes.each do |like|%>
      <%if like.user == current_user then already_liked = true end%>
      <%end%>
      <%case already_liked %>
      <%when false %>
      <form action="<%= gossip_likes_path(@gossip.id)%>" method='post'>
        <%= submit_tag "👍", class: "btn btn-secondary"%>
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      </form>
      <%when true %>
       <a class= "btn btn-success active" data-method= "delete" href="<%= gossip_like_path(@gossip.id) %>"> 👍</a>
      <%end%>


    </div>
  </div>
  <div class="card-footer text-muted">
    <p>
      <% @gossip.tags.each do |tag| %>
      <%= tag.title %>
      <% end %>
    </p>
    <p>
      Modifié le : <%= @gossip.updated_at.strftime("%Y-%m-%d %H:%M:%S") %>
    </p>
    <a href="<%= root_path%>" class="btn btn-primary">Page d'accueil</a>
  </div>

app/views/users/hidden.html.erb
<div class="text-center">
    <h1>Bienvenue <%= @person.capitalize %>&nbsp;</h1>
    <p>Ici c'est notre super site de potins.<br/>Il est chouette, non ?</p>
    <a href="<%= root_path%>" class="btn btn-primary">Retour</a>
</div>

app/views/users/new.html.erb
<% user = @user ? @user : User.new%>

<% if flash[:error] %>
<div class="alert alert-danger">
  <%= flash[:error]%>
</div>
<% end %>

<div class="card text-center">
  <div class="card-header">
    <h1>Salut petit nouveau ! </h1>
  </div>

<!-- formulaire de création de gossip form_tag -->

  <%= form_tag url_for(action: 'create'), method: 'POST', class:"card-body" do %>
     <div class="form-group">
      <%= label_tag 'last_name', 'Nom' %>
      <%= text_field_tag 'last_name', user.last_name, class: "form-control", required: "required" %>
    </div>
    <div class="form-group">
      <%= label_tag 'first_name', 'Prénom' %>
      <%= text_field_tag 'first_name', user.first_name, class: "form-control", required: "required" %>
    </div>
    <div class="form-group">
      <%= label_tag 'age', 'Âge' %>
      <%= number_field_tag 'age', user.age, class: "form-control", required: "required" %>
    </div>
    <div class="form-group">
      <%= label_tag 'email', 'E-mail' %>
      <%= email_field_tag 'email', user.email, class: "form-control", required: "required" %>
    </div>
    <div class="form-group">
        <%= label_tag 'city', 'Ville' %>
        <select id="city" name= "city" required>
        <option disabled selected>Choisis ta ville.</option>
        <% @cities.each do |city| %>
            <option value="<%= city.id %>"><%= city.name %></option>
        <% end%>
        </select>
    </div>
    <div class="form-group">
      <%= label_tag 'description', 'Description' %>
      <%= text_area_tag 'description', user.description, class: "form-control", required: "required" %>
    </div>
    <div class="form-group">
      <%= label_tag 'password', 'Mot de passe' %>
      <%= password_field_tag 'password', nil, class: "form-control", required: "required" %>
    </div>
    <div class="form-group">
      <%= label_tag 'password_confirmation', 'Confirmation' %>
      <%= password_field_tag 'password_confirmation', nil, class: "form-control" %>
    </div> 
    <div class="form-group">
      <%= submit_tag "Créer user", class: "btn btn-primary"%>
    </div>
  <% end %>

<!-- ... -->
  <div class="card-footer text-muted">
    <p>
      <br/>
      <a href="<%= root_path%>" class="btn btn-primary">Retour à l'accueil </a>
    </p>
  </div>
</div>

app/views/users/show.html.erb
<div class="card text-center">
  <div class="card-header">
    <h1><%= @author.first_name + " " + @author.last_name %></h1>
  </div>
  <div class="card-body text-left">
    <p><strong>Nom&nbsp;:</strong> <%= @author.last_name %></p>
    <p><strong>Prénom&nbsp;:</strong> <%= @author.first_name %></p>
    <p><strong>Âge&nbsp;:</strong> <%= @author.age %></p>
    <p><strong>E-mail&nbsp;:</strong> <%= @author.email %></p>
    <p><strong>Adresse&nbsp;:</strong> <%= link_to @author.city.name, city_path(@author.city.id) %>  ( <%= @author.city.zip_code %> )</p>
    <dl>
      <dt><strong>Description&nbsp;:</strong></dt>
      <dd><%= @author.description %></dd>
    </div>
    <hr/>
    <h3>Ses potins&nbsp;:</h3>
    <p>
      <% @author.gossips.each do |gossip| %>
      <!--Likes-->
      <% already_liked=false%>
      <% gossip.likes.each do |like|%>
      <%if like.user == current_user then already_liked = true end%>
      <%end%>
      <%case already_liked %>
      <%when false %>
      <a class= "btn btn-secondary" data-method= "post" href="<%= gossip_likes_path(id: gossip.id, gossip_id: gossip.id) %>"> 👍</a>
      <%when true %>
      <a class= "btn btn-success active" data-method= "delete" href="<%= gossip_like_path(id: gossip.id, gossip_id: gossip.id) %>"> 👍</a>
      <%end%>
      <%= link_to gossip.title + " (#{gossip.likes_amount.to_s} likes)", gossip_path(gossip.id) %><br/>
      <% end %>
    </p>
    <div class="card-footer text-muted text-center">
      <a href="<%= root_path%>" class="btn btn-primary">Page d'accueil</a>
    </div>