config/routes.rb
Rails.application.routes.draw do
  resources :gossips do
    resources :comments, except: [:index, :new, :show]
    resources :likes, only: [:create, :destroy]
  end
  resources :users
  resources :cities
  resources :sessions, only: [:new, :create, :destroy]
  root 'gossips#index'
  get 'team', to: 'static#team'
  get 'contact', to: 'static#contact'
  get 'hidden/:person', to: 'user#hidden', as: 'hidden_person'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  validates :name,
    presence: true
  validates :zip_code,
    presence: true,
    uniqueness: true,
    format: { with: /\A(([0-8][0-9])|(9[0-5])|(2[ab]))[0-9]{3}\z/, message: "please enter a valid french zip code" }

    has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content,
    presence: true
  belongs_to :user
  belongs_to :gossip  
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title,
  presence: true,
  length: {minimum: 3, maximum: 14}
  validates :content,
  presence: true

  belongs_to :user
  has_many :tag_gossip_links
  has_many :tags, through: :tag_gossip_links
  has_many :comments
  has_many :likes


  def likes_amount
    self.likes.length
  end

end

app/models/like.rb
class Like < ApplicationRecord
validates :gossip_id, uniqueness: { scope: :user_id,
    message: "only one like per user per gossip" }

  belongs_to :gossip
  belongs_to :user
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  validates :content, 
    presence: true

  belongs_to :sender, class_name: "User"
  has_many :recipient_to_pm_links, foreign_key: 'received_message_id'
  has_many :recipients, foreign_key: 'recipient_id', class_name: "User", through: :recipient_to_pm_links
end

app/models/recipient_to_pm_link.rb
class RecipientToPmLink < ApplicationRecord
  belongs_to :recipient, class_name: "User"
  belongs_to :received_message, class_name: "PrivateMessage"
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :title, 
    presence: true
    
  has_many :tag_gossip_links
  has_many :gossips, through: :tag_gossip_links
end

app/models/tag_gossip_link.rb
class TagGossipLink < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :description, presence: true
  validates :age, presence: true
  validates :password, presence: true, length: {minimum: 6}

  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :recipient_to_pm_links, foreign_key: 'recipient_id'
  has_many :received_messages, foreign_key: 'received_message_id', class_name: "PrivateMessage", through: :recipient_to_pm_links
  has_many :comments
  has_many :likes
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user, only: [:create, :destroy]

  def create
    @like = Like.create(user: current_user, gossip: Gossip.find(params[:gossip_id]))
    puts @like.errors.messages
    redirect_back(fallback_location: root_path)
  end

  def destroy
    likes = Like.where(user: current_user, gossip: Gossip.find(params[:id]))
    likes.each do |like|
      like.destroy
    end
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @author = User.find(params[:id])
  end

  def hidden
    @person = params[:person]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @cities = get_city
  end

  def create
    begin
      @user = User.new(
        first_name: params[:first_name],
        last_name: params[:last_name],
        age:params[:age],
        city: City.find(params[:city]),
        description: params[:description],
        email: params[:email],
        password: params[:password],
        password_confirmation: params[:password_confirmation]
        )

      if @user.save
        flash.now[:success] = "Nouvel utilisateur enregistré"
        log_in(@user)
        redirect_to root_path
      else
        flash.now[:error] = "Tu as du oublier de remplir des informations mon petit chat"
        @cities = get_city
        render 'new'
      end
    rescue Exception => e
      flash.now[:error] = e.message
      @cities = get_city
      render "new"
    end
  end

  def show
    @author = User.find(params[:id])
  end

  def hidden
    @person = params[:person]
  end

  private

  def get_city
   City.all.order("name")
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end

  def is_gossip_author?
    unless current_user == User.find_by(gossips: Gossip.find(params[:id]))
      flash[:danger] = "Tu n'es pas l'auteur de ce potin."
      redirect_to root_path
    end
  end

  def is_comment_author?
    unless current_user == User.find_by(comments: Comment.find(params[:id]))
      flash[:danger] = "Tu n'es pas l'auteur de ce commentaire."
      redirect_to root_path
    end
  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fr">
<head>
  <title>The Gossip Project : Final Version Of The Gods</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="<%= root_path %>">The Gossip Project &trade;</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="<%= team_path %>">Team</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= contact_path %>">Contact</a>
          </li>
          <% unless session[:user_id] %>
          <li class="nav-item">
            <div class="dropdown show">
              <a class="nav-link dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Connexion
              </a>
              <div class="dropdown-menu bg-dark" aria-labelledby="dropdownMenuLink">
                <a class="nav-link" href="<%= new_user_path %>">S'inscrire</a>
                <a class="nav-link" href="<%= new_session_path %>">Se connecter</a>
              </div>
          </li>
          <% else%>
          <li>
            <a href="<%= session_path(session[:user_id]) %>" class="nav-link" data-method= "delete">Se deconnecter</a>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <!-- Page Content -->
  <main class="container">
    <%= yield %>
  </main>
  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; The best Team 2019</p>
    </div>
  </footer>
</body>
</html>